import './globals.css'
import './styles/globals.sass'

import { Header } from './components/Header'

export const metadata = {
  title: "Mauricio Paternina's portfolio",
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
